#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <syslog.h>
#include <string.h>

int main(int argc, char **argv)
{
	pid_t pid;
	pid_t sid;

	pid = fork();
	if(pid < 0) {
		exit(EXIT_FAILURE);
	}
	if(pid > 0) {
		exit(EXIT_SUCCESS);
	}

	umask(0);
	
	sid = setsid();
	if(sid < 0) {
		/*log the failure*/
		exit(EXIT_FAILURE);
	}

	if(chdir("/") < 0) {
		/*log the failure*/
		exit(EXIT_FAILURE);
	}
	
	close(STDIN_FILENO);
	close(STDOUT_FILENO);
	close(STDERR_FILENO);

	/*daemon specific initilization goes here */
	while(1){
		//do something here
		//one log example 
		syslog(LOG_INFO, "this is a log generated by %s\n", argv[0]);
		sleep(10);
	}
	

	return 0;
}
